language: php

env:
  - SILEX_VERSION="1.0.*" SWAGGER_VERSION="0.8.*"
  - SILEX_VERSION="1.1.*" SWAGGER_VERSION="0.8.*"
  - SILEX_VERSION="1.2.*" SWAGGER_VERSION="0.8.*"
  - SILEX_VERSION="1.0.*" SWAGGER_VERSION="0.9.*"
  - SILEX_VERSION="1.1.*" SWAGGER_VERSION="0.9.*"
  - SILEX_VERSION="1.2.*" SWAGGER_VERSION="0.9.*"
  - SILEX_VERSION="2.*" SWAGGER_VERSION="0.9.*"

before_script:
  - composer require silex/silex:${SILEX_VERSION}
  - composer require zircote/swagger-php:${SWAGGER_VERSION}
  - composer install --dev --prefer-source

script: vendor/bin/phpunit

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
